import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/Provider";
import DefaultLayout from "@/components/layouts/default-layout/DefaultLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ReduxProvider>
          <DefaultLayout>
            <div className="min-h-[40vh]">{children}</div>
            {/* <ShoppingCardDrawer  /> */}
          </DefaultLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
